# first building react project, using node base image
FROM node:15.11.0-alpine as build-stage

# setting working dir inside container
WORKDIR /react-app

# required to install packages
COPY /react-app/package.*json ./

# installing npm packages
RUN npm install --silent

#RUN npm install react-scripts@3.4.0 -g --silent 


# copying over react source material
COPY  /react-app/src ./src

# copying over further react material
COPY  /react-app/public ./public

# copying over our nginx config file
COPY /nginx/default.conf ./

# creating production build to serve through nginx
RUN npm run build

# starting second, nginx build-stage
FROM nginx:stable-alpine

# removing default nginx config file
RUN rm /etc/nginx/conf.d/default.conf

# copying production build from last stage to serve through nginx
COPY --from=build-stage /react-app/build/ /usr/share/nginx/html

# copying our nginx config
COPY  nginx/default.conf /etc/nginx/conf.d/

# exposing port 8080 on container
EXPOSE 3000

CMD ["nginx", "start"]