version: "3"


networks :
  frontend_prod:

  dockergateway_backend_auth:
    external: true
      

services:
  frontend_nginx: 
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend_nginx_prod
    ports:
      - "8080:80"
    networks: 
      - frontend_prod
      - dockergateway_backend_auth
    environment: 
      - CHOKIDAR_USEPOLLING=true
