version: "3"


networks :
  frontend:

  authprojectauth_backend_auth:
    external: true
      

services:
  frontend_nginx: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend_nginx
    ports:
      - "3000:80"
    networks: 
      - frontend
      - authprojectauth_backend_auth
