version: "3"


networks :
  frontend_dev:

  dockergateway_backend_auth:
    external: true
      

services:
  frontend_nginx: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend_nginx_dev
    ports:
      - "3001:3000"
    
    networks: 
      - frontend_dev
      - dockergateway_backend_auth
    environment: 
      - CHOKIDAR_USEPOLLING=true
